Log DS, joystick, and drivetrain
frc8016/2023-ChargedUp pull request #3
Opened 2023-03-31 18:14 UTC by Dan-The-Alien

This code has been tested in simulation, but not on the robot. It should log the current and temperature of each of the drive motors to a file on the RoboRIO, which we can retrieve in the pit if needed

2023-03-31 18:16 UTC, Dan-The-Alien commented
Oh yeah, sorry about the settings file being included. I can pull that out into a different PR if you want, I didn't realize that file was tracked, but the only change I made is for the spotless plugin in VSCode to automatically format the file on save

2023-03-31 21:36 UTC, CarloWoolsey requested changes
Looks great! I have requested a few formatting changes.

2023-03-31 21:36 UTC, CarloWoolsey commented on .vscode/settings.json
> +
I'm fine with leaving changes to ``.vscode/settings.json`` in this commit --the changes will reduce formatting overhead for new members.

2023-03-31 21:36 UTC, CarloWoolsey commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +  private DataLog log = DataLogManager.getLog();
```suggestion
  private DataLog m_log = DataLogManager.getLog();
```

2023-03-31 21:36 UTC, CarloWoolsey commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +  // private DoubleLogEntry l_topLeftMotorCurrent = new DoubleLogEntry(log,
For the sake of clean code, I might suggest that we remove the commented out code blocks logging a 3rd drivetrain motor (which doesn't currently exist).

2023-04-01 00:22 UTC, CarloWoolsey approved these changes
Looks great!

2023-04-01 00:23 UTC, merged